import sys
import sqlite3
from PyQt5 import QtWidgets,QtGui,QtCore

class Login(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()
        self.baglantiOlustur()
    def baglantiOlustur(self):
        baglanti = sqlite3.connect("Kayitlar.db")
        self.cursor = baglanti.cursor()
        self.cursor.execute("Create Table if not exists Uyeler (kullanici_adi TEXT,parola TEXT)")
        baglanti.commit()
    def initUI(self):
        self.label1 = QtWidgets.QLabel()
        self.label2 = QtWidgets.QLabel()
        self.label3 = QtWidgets.QLabel("")
        self.label1.setText("E-mail:")
        self.label2.setText(" Şifre:")
        self.girisYazisi = QtWidgets.QLabel()
        self.girisYazisi.setText("HOŞGELDİNİZ")
        self.KullaniciAdi = QtWidgets.QLineEdit()
        self.parola = QtWidgets.QLineEdit()
        self.parola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.girisButon = QtWidgets.QPushButton("GİRİŞ")
        self.sifreUnuttum = QtWidgets.QPushButton("Şifremi Unuttum")
        self.h_box = QtWidgets.QHBoxLayout()
        self.h_box.addStretch()
        self.h_box.addWidget(self.girisYazisi)
        self.h_box.addStretch()
        self.h_box1 = QtWidgets.QHBoxLayout()
        self.h_box1.addStretch()
        self.h_box1.addWidget(self.label1)
        self.h_box1.addWidget(self.KullaniciAdi)
        self.h_box1.addStretch()
        self.h_box2 = QtWidgets.QHBoxLayout()
        self.h_box2.addStretch()
        self.h_box2.addWidget(self.label2)
        self.h_box2.addWidget(self.parola)
        self.h_box2.addStretch()
        self.h_box3 = QtWidgets.QHBoxLayout()
        self.h_box3.addStretch()
        self.h_box3.addWidget(self.label3)
        self.h_box3.addStretch()
        self.h_box4 = QtWidgets.QHBoxLayout()
        self.h_box4.addStretch()
        self.h_box4.addWidget(self.girisButon)
        self.h_box4.addWidget(self.sifreUnuttum)
        self.h_box4.addStretch()
        self.v_box = QtWidgets.QVBoxLayout()
        self.v_box.addStretch()
        self.v_box.addLayout(self.h_box)
        self.v_box.addLayout(self.h_box1)
        self.v_box.addLayout(self.h_box2)
        self.v_box.addLayout(self.h_box3)
        self.v_box.addLayout(self.h_box4)
        self.v_box.addStretch()
        self.setLayout(self.v_box)
        self.setWindowTitle("Login Uygulaması")
        self.girisButon.clicked.connect(self.Kontrol)
        self.sifreUnuttum.clicked.connect(self.kodAl)
        self.show()
    def Kontrol(self):
        id = self.KullaniciAdi.text()
        pw = self.parola.text()
        self.cursor.execute("Select * from Uyeler where kullanici_adi = ? and parola = ?",(id,pw))
        veri = self.cursor.fetchall()
        if len(veri) == 0:
            self.KullaniciAdi.clear()
            self.parola.clear()
            self.label3.setText("Kullanıcı adı veya parola hatalı!")
        else:
            self.label3.setText("Giriş Başarılı")
    def kodAl(self):
        self.girisYazisi.setText("Onay kodu gönderilecek e-maili giriniz.")
        self.label2.close()
        self.label3.close()
        self.parola.close()
        self.girisButon.close()
        self.sifreUnuttum.setText("Gönder")
        self.sifreUnuttum.clicked.connect(self.kodGonder)
    def kodGonder(self):
        self.KullaniciAdi.clear()
        self.girisYazisi.setText("E-mail adresine gönderilen onay kodunu giriniz.")
        self.label1.setText("Onay Kodu: ")
        self.sifreUnuttum.setText("Onayla")
        self.sifreUnuttum.clicked.connect(self.Onayla)
    def Onayla(self):
        pass

app = QtWidgets.QApplication(sys.argv)
kayit = Login()
sys.exit(app.exec_())